import "@/app/_styles/globals.css";

export const metadata = {
  title: "DEMO: Bankist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
